### PR TITLE
feat(wip): support to session replay

### PR DESCRIPTION
**Pull request by thisames**
## :bulb: Motivation and Context

#69 

## :pencil: Checklist

- [ ] I reviewed the submitted code.
- [ ] I added tests to verify the changes.
- [ ] I updated the docs if needed.
- [ ] No breaking change or entry added to the changelog.

### CODE REVIEW

**Comment by marandaneto** [comment]
Amazing @thisames will take a look.

**Comment by thisames** [comment]
Everything is going well. In theory, the replay already works. However, I still need to thoroughly analyze the code and adjust other details. I also need to organize the folder structure and check if there is any code smell.

Additionally, here are the main tasks that are currently a priority:
[x] masks navigation context
[  ] Regular and improve the debounce (It currently works ok, but not enough)
[  ] Improve performance (It currently works ok, but not enough)
[  ] Add a solution to perfectly synchronize the mask with the current screenshot (maybe a manual schedule or queue?)


https://github.com/user-attachments/assets/4777577b-722c-4e94-8021-72783c046a2c

**Comment by marandaneto** [comment]
@thisames look at this [PR](https://github.com/PostHog/posthog-flutter/pull/117) since I need to get this merged in first and will conflict with a few things for you

**Comment by thisames** [comment]
> @thisames look at this [PR](https://github.com/PostHog/posthog-flutter/pull/117) since I need to get this merged in first and will conflict with a few things for you

I think you can merge this https://github.com/PostHog/posthog-flutter/pull/117. Then I'll pull it and resolve the conflicts. But there's nothing that will impact my PR that much. I just need to adapt the initialization settings that I added to the style that you implemented.

https://github.com/PostHog/posthog-flutter/blob/197002162df1ddc9fbd5acf524a933a1ddbd1ae7/lib/src/posthog.dart#L25-L38

from what I understand, my init is equivalent to your setup.

```dart
Future<void> setup(PostHogConfig config) => _posthog.setup(config);
```

**Comment by xkxeeshankhan** [comment]
hello @thisames Hope you are doing well

I see you guys are working on the session recording is this feature will be available for Flutter web as well?

**Comment by thisames** [comment]
> hello @thisames Hope you are doing well
> 
> I see you guys are working on the session recording is this feature will be available for Flutter web as well?

I think that @marandaneto may say better about that

**Pull request merged**
