### PR TITLE
[#96] Fixes PostHogConfig.defaultValue not being found

### PR DESCRIPTION
**Pull request by dancamdev**
## :bulb: Motivation and Context

This is related to issue #96 and fixes it.

## :green_heart: How did you test it?
run `flutter build apk` and it worked.

## :pencil: Checklist

- [x] I reviewed the submitted code.
- [ ] I added tests to verify the changes.
- [x] I updated the docs if needed.
- [ ] No breaking change or entry added to the changelog.

### CODE REVIEW

**Comment by karabanovbs** [comment]
Are this fix will broke capability with previous [posthog-android](https://github.com/PostHog/posthog-android)?
Looks like that this version shouldn`t working with [3.1.16](https://github.com/PostHog/posthog-android/releases/tag/3.1.16).

**Comment by dancamdev** [comment]
I don't know but happy to fix anything that comes up if you have any insights

**Comment by karabanovbs** [comment]
> I don't know but happy to fix anything that comes up if you have any insights

set this version lower then 3.1.17 can help i think https://github.com/PostHog/posthog-flutter/blob/main/android/build.gradle#L58

Im try to do it locally

**Comment by dancamdev** [comment]
Alright - wondering, why do you care about < 3.1.17 if you're depending on updated versions internally anyway?

**Comment by karabanovbs** [comment]
because 3.1.17 have breaking changes

**Comment by marandaneto** [comment]
Oh you beat me to it https://github.com/PostHog/posthog-flutter/pull/98

**Comment by marandaneto** [comment]
@dancamdev would you like to update the changelog to match https://github.com/PostHog/posthog-flutter/pull/98 or should I merge mine?

**Comment by dancamdev** [comment]
I'll edit. Thanks

**Comment by marandaneto** [comment]
Closing it in favor of https://github.com/PostHog/posthog-flutter/pull/98 since the CI is green and I want to cut a release to fix it, will give you credits in the release, thanks @dancamdev

**Pull request closed without merging**
